// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Header(Props) {
  var text = Props.text;
  return React.createElement("header", {
              className: "App-header"
            }, React.createElement("h2", undefined, text));
}

var make = Header;

exports.make = make;
/* react Not a pure module */
