// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Movie(Props) {
  var movie = Props.movie;
  return React.createElement("div", {
              className: "movie"
            }, React.createElement("h2", undefined, movie[/* title */1]), React.createElement("div", undefined, React.createElement("img", {
                      alt: "The movie titled " + movie[/* title */1],
                      src: movie[/* poster */2],
                      width: "200"
                    })), React.createElement("p", undefined, movie[/* year */3]));
}

var make = Movie;

exports.make = make;
/* react Not a pure module */
