// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Search(Props) {
  var searchFunc = Props.searchFunc;
  var match = React.useState((function () {
          return "";
        }));
  var setInput = match[1];
  var input = match[0];
  var handleSearchInputChanges = function ($$event) {
    return Curry._1(setInput, $$event.target.value);
  };
  var callSearchFunction = function ($$event) {
    $$event.preventDefault();
    return Curry._1(searchFunc, input);
  };
  return React.createElement("form", {
              className: "search",
              onSubmit: callSearchFunction
            }, React.createElement("input", {
                  type: "text",
                  value: input,
                  onChange: handleSearchInputChanges
                }), React.createElement("button", {
                  type: "submit"
                }, "SEARCH"));
}

var make = Search;

exports.make = make;
/* react Not a pure module */
